print('olá, mundo')
print('batata')
print('tudo bem?')
print('eu te amo')
print('queria dinheiro')
print('bom dia')
print('eu amo animais')
print('quero comer')
print('quem é a pessoa mais velha do mundo')
print('será que um dia vai existir o iphone 7000 ?')